package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Atributo generated by hbm2java
 */
@Entity
@Table(name = "Atributo")
public class Atributo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 362176579016825085L;
	
	private Integer idAtributo;
	private String strAtributo;

	public Atributo() {
	}

	public Atributo(Integer idAtributo) {
		this.idAtributo = idAtributo;
	}

	public Atributo(Integer idAtributo, String strAtributo) {
		this.idAtributo = idAtributo;
		this.strAtributo = strAtributo;
	}

	@Id
	@Column(name = "id_atributo")
	public Integer getIdAtributo() {
		return this.idAtributo;
	}

	public void setIdAtributo(Integer idAtributo) {
		this.idAtributo = idAtributo;
	}

	@Column(name = "str_atributo", length = 2000000000)
	public String getStrAtributo() {
		return this.strAtributo;
	}

	public void setStrAtributo(String strAtributo) {
		this.strAtributo = strAtributo;
	}

}
