package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Atributo generated by hbm2java
 */
@Entity
@Table(name = "Caso")
public class Caso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5026198569124306257L;
	private Integer idCaso;
	private String strTitulo;
	private String strDescricao;
	private Integer idFuncaoGeral;
	private Integer idTipo;
	private Integer intAno;

	public Caso() {
	}

	public Caso(Integer idCaso) {
		this.idCaso = idCaso;
	}

	public Caso(Integer idCaso, String strTitulo, String strDescricao, Integer idFuncaoGeral) {
		this.idCaso = idCaso;
		this.strTitulo = strTitulo;
	}

	@Id
	@Column(name = "id_caso")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdCaso() {
		return this.idCaso;
	}

	public void setIdCaso(Integer idCaso) {
		this.idCaso = idCaso;
	}

	@Column(name = "str_titulo", length = 2000000000)
	public String getStrTitulo() {
		return this.strTitulo;
	}

	public void setStrTitulo(String strTitulo) {
		this.strTitulo = strTitulo;
	}

	@Column(name = "str_descricao", length = 2000000000)
	public String getStrDescricao() {
		return this.strDescricao;
	}

	public void setStrDescricao(String strDescricao) {
		this.strDescricao = strDescricao;
	}
	
	@Column(name = "id_funcao_geral")
	public Integer getIdFuncaoGeral() {
		return this.idFuncaoGeral;
	}

	public void setIdFuncaoGeral(Integer idFuncaoGeral) {
		this.idFuncaoGeral = idFuncaoGeral;
	}
	
	@Column(name = "id_tipo")
	public Integer getIdTipo() {
		return idTipo;
	}

	public void setIdTipo(Integer idTipo) {
		this.idTipo = idTipo;
	}

	@Column(name = "int_ano")
	public Integer getIntAno() {
		return intAno;
	}

	public void setIntAno(Integer intAno) {
		this.intAno = intAno;
	}

	public String toString(){
		return this.idCaso + " - " + this.strTitulo;
	}
}
