/*
 * 
 */
package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * Atributo generated by hbm2java.
 */
@Entity
@Table(name = "Caso")
public class Caso implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -5026198569124306257L;
	
	/** The id caso. */
	private Integer idCaso;
	
	/** The str titulo. */
	private String strTitulo;
	
	/** The str descricao. */
	private String strDescricao;
	
	/** The id funcao geral. */
	private Integer idFuncaoGeral;
	
	/** The id tipo. */
	private Integer idTipo;
	
	/** The int ano. */
	private Integer intAno;

	/**
	 * Instantiates a new caso.
	 */
	public Caso() {
	}

	/**
	 * Instantiates a new caso.
	 *
	 * @param idCaso the id caso
	 */
	public Caso(Integer idCaso) {
		this.idCaso = idCaso;
	}

	/**
	 * Instantiates a new caso.
	 *
	 * @param idCaso the id caso
	 * @param strTitulo the str titulo
	 * @param strDescricao the str descricao
	 * @param idFuncaoGeral the id funcao geral
	 */
	public Caso(Integer idCaso, String strTitulo, String strDescricao, Integer idFuncaoGeral) {
		this.idCaso = idCaso;
		this.strTitulo = strTitulo;
	}

	/**
	 * Gets the id caso.
	 *
	 * @return the id caso
	 */
	@Id
	@Column(name = "id_caso")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdCaso() {
		return this.idCaso;
	}

	/**
	 * Sets the id caso.
	 *
	 * @param idCaso the new id caso
	 */
	public void setIdCaso(Integer idCaso) {
		this.idCaso = idCaso;
	}

	/**
	 * Gets the str titulo.
	 *
	 * @return the str titulo
	 */
	@Column(name = "str_titulo", length = 2000000000)
	public String getStrTitulo() {
		return this.strTitulo;
	}

	/**
	 * Sets the str titulo.
	 *
	 * @param strTitulo the new str titulo
	 */
	public void setStrTitulo(String strTitulo) {
		this.strTitulo = strTitulo;
	}

	/**
	 * Gets the str descricao.
	 *
	 * @return the str descricao
	 */
	@Column(name = "str_descricao", length = 2000000000)
	public String getStrDescricao() {
		return this.strDescricao;
	}

	/**
	 * Sets the str descricao.
	 *
	 * @param strDescricao the new str descricao
	 */
	public void setStrDescricao(String strDescricao) {
		this.strDescricao = strDescricao;
	}
	
	/**
	 * Gets the id funcao geral.
	 *
	 * @return the id funcao geral
	 */
	@Column(name = "id_funcao_geral")
	public Integer getIdFuncaoGeral() {
		return this.idFuncaoGeral;
	}

	/**
	 * Sets the id funcao geral.
	 *
	 * @param idFuncaoGeral the new id funcao geral
	 */
	public void setIdFuncaoGeral(Integer idFuncaoGeral) {
		this.idFuncaoGeral = idFuncaoGeral;
	}
	
	/**
	 * Gets the id tipo.
	 *
	 * @return the id tipo
	 */
	@Column(name = "id_tipo")
	public Integer getIdTipo() {
		return idTipo;
	}

	/**
	 * Sets the id tipo.
	 *
	 * @param idTipo the new id tipo
	 */
	public void setIdTipo(Integer idTipo) {
		this.idTipo = idTipo;
	}

	/**
	 * Gets the int ano.
	 *
	 * @return the int ano
	 */
	@Column(name = "int_ano")
	public Integer getIntAno() {
		return intAno;
	}

	/**
	 * Sets the int ano.
	 *
	 * @param intAno the new int ano
	 */
	public void setIntAno(Integer intAno) {
		this.intAno = intAno;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	public String toString(){
		return this.idCaso + " - " + this.strTitulo;
	}
}
