package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Conceito generated by hbm2java
 */
@Entity
@Table(name = "Conceito")
public class Conceito implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1388486716127624414L;
	
	private Integer idConceito;
	private String strConceito;
	private Integer imgConceito;
	private String descConceito;

	public Conceito() {
	}

	public Conceito(Integer idConceito) {
		this.idConceito = idConceito;
	}

	public Conceito(Integer idConceito, String strConceito,
			Integer imgConceito, String descConceito) {
		this.idConceito = idConceito;
		this.strConceito = strConceito;
		this.imgConceito = imgConceito;
		this.descConceito = descConceito;
	}

	@Id
	@Column(name = "id_conceito")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdConceito() {
		return this.idConceito;
	}

	public void setIdConceito(Integer idConceito) {
		this.idConceito = idConceito;
	}

	@Column(name = "str_conceito")
	public String getStrConceito() {
		return this.strConceito;
	}

	public void setStrConceito(String strConceito) {
		this.strConceito = strConceito;
	}

	@Column(name = "img_conceito")
	public Integer getImgConceito() {
		return this.imgConceito;
	}

	public void setImgConceito(Integer imgConceito) {
		this.imgConceito = imgConceito;
	}

	@Column(name = "desc_conceito", length = 2000000000)
	public String getDescConceito() {
		return this.descConceito;
	}

	public void setDescConceito(String descConceito) {
		this.descConceito = descConceito;
	}

}
