/*
 * 
 */
package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * Conceito generated by hbm2java.
 */
@Entity
@Table(name = "Conceito")
public class Conceito implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1388486716127624414L;
	
	/** The id conceito. */
	private Integer idConceito;
	
	/** The str conceito. */
	private String strConceito;
	
	/** The img conceito. */
	private Integer imgConceito;
	
	/** The desc conceito. */
	private String descConceito;

	/**
	 * Instantiates a new conceito.
	 */
	public Conceito() {
	}

	/**
	 * Instantiates a new conceito.
	 *
	 * @param idConceito the id conceito
	 */
	public Conceito(Integer idConceito) {
		this.idConceito = idConceito;
	}

	/**
	 * Instantiates a new conceito.
	 *
	 * @param idConceito the id conceito
	 * @param strConceito the str conceito
	 * @param imgConceito the img conceito
	 * @param descConceito the desc conceito
	 */
	public Conceito(Integer idConceito, String strConceito,
			Integer imgConceito, String descConceito) {
		this.idConceito = idConceito;
		this.strConceito = strConceito;
		this.imgConceito = imgConceito;
		this.descConceito = descConceito;
	}

	/**
	 * Gets the id conceito.
	 *
	 * @return the id conceito
	 */
	@Id
	@Column(name = "id_conceito")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdConceito() {
		return this.idConceito;
	}

	/**
	 * Sets the id conceito.
	 *
	 * @param idConceito the new id conceito
	 */
	public void setIdConceito(Integer idConceito) {
		this.idConceito = idConceito;
	}

	/**
	 * Gets the str conceito.
	 *
	 * @return the str conceito
	 */
	@Column(name = "str_conceito")
	public String getStrConceito() {
		return this.strConceito;
	}

	/**
	 * Sets the str conceito.
	 *
	 * @param strConceito the new str conceito
	 */
	public void setStrConceito(String strConceito) {
		this.strConceito = strConceito;
	}

	/**
	 * Gets the img conceito.
	 *
	 * @return the img conceito
	 */
	@Column(name = "img_conceito")
	public Integer getImgConceito() {
		return this.imgConceito;
	}

	/**
	 * Sets the img conceito.
	 *
	 * @param imgConceito the new img conceito
	 */
	public void setImgConceito(Integer imgConceito) {
		this.imgConceito = imgConceito;
	}

	/**
	 * Gets the desc conceito.
	 *
	 * @return the desc conceito
	 */
	@Column(name = "desc_conceito", length = 2000000000)
	public String getDescConceito() {
		return this.descConceito;
	}

	/**
	 * Sets the desc conceito.
	 *
	 * @param descConceito the new desc conceito
	 */
	public void setDescConceito(String descConceito) {
		this.descConceito = descConceito;
	}

}
