package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FuncaoParcial generated by hbm2java
 */
@Entity
@Table(name = "FuncaoCaso")
public class FuncaoCaso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4908688476247627544L;
	
	//============================================================
	//ID deste elemento
	private Integer idFuncaoCaso;
	//ID da funcao quese desdobra nesta
	private Integer idFuncaoPai;
	//Identificador da funcao
	private Integer idFuncao;
	//Se função elementar, será utilziada na matriz
	private boolean bolElementar;
	//Tipo funcao de produto
	private Integer tipoFuncao;
	//Grau de necessidade (necessária/derivada)
	private Integer tipoNecessidade;
	//Tipo do efeito (Indiferente, prevenção, correção)
	private Integer tipoEfeito;
	//Escopo abrangido (Informação,Potência, mecânica, controle)
	private Integer tipoEscopo;
	//============================================================
	
	public FuncaoCaso() {
	}

	public FuncaoCaso(Integer idFuncao) {
		this.idFuncaoCaso = idFuncao;
	}

	//============================================================
	@Id
	@Column(name = "id_funcao_caso")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdFuncaoCaso() {
		return this.idFuncaoCaso;
	}

	public void setIdFuncaoCaso(Integer idFuncaoCaso) {
		this.idFuncaoCaso = idFuncaoCaso;
	}

	//============================================================
	@Column(name = "id_funcao_pai")
	public Integer getIdFuncaoPai() {
		return this.idFuncaoPai;
	}

	public void setIdFuncaoPai(Integer idFuncaoPai) {
		this.idFuncaoPai = idFuncaoPai;
	}

	//============================================================
	@Column(name = "id_funcao")
	public Integer getIdFuncao() {
		return idFuncao;
	}

	public void setIdFuncao(Integer idFuncao) {
		this.idFuncao = idFuncao;
	}

	//============================================================
	@Column(name = "bol_elementar")
	public boolean getBolElementar() {
		return bolElementar;
	}

	public void setBolElementar(boolean bolElementar) {
		this.bolElementar = bolElementar;
	}

	//============================================================
	@Column(name = "tipo_funcao")
	public Integer getTipoFuncao() {
		return tipoFuncao;
	}

	public void setTipoFuncao(Integer tipoFuncao) {
		this.tipoFuncao = tipoFuncao;
	}

	//============================================================
	@Column(name = "tipo_necessidade")
	public Integer getTipoNecessidade() {
		return tipoNecessidade;
	}

	public void setTipoNecessidade(Integer tipoNecessidade) {
		this.tipoNecessidade = tipoNecessidade;
	}

	//============================================================
	@Column(name = "tipo_efeito")
	public Integer getTipoEfeito() {
		return tipoEfeito;
	}

	public void setTipoEfeito(Integer tipoEfeito) {
		this.tipoEfeito = tipoEfeito;
	}

	//============================================================
	@Column(name = "tipo_escopo")
	public Integer getTipoEscopo() {
		return tipoEscopo;
	}

	public void setTipoEscopo(Integer tipoEscopo) {
		this.tipoEscopo = tipoEscopo;
	}
}
