/*
 * 
 */
package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * FuncaoParcial generated by hbm2java.
 */
@Entity
@Table(name = "FuncaoCaso")
public class FuncaoCaso implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -4908688476247627544L;
	
	//============================================================
	/** The id funcao caso. */
	//ID deste elemento
	private Integer idFuncaoCaso;
	
	/** The id funcao pai. */
	//ID da funcao quese desdobra nesta
	private Integer idFuncaoPai;
	
	/** The id funcao. */
	//Identificador da funcao
	private Integer idFuncao;
	
	/** The bol elementar. */
	//Se função elementar, será utilziada na matriz
	private boolean bolElementar;
	
	/** The tipo funcao. */
	//Tipo funcao de produto
	private Integer tipoFuncao;
	
	/** The tipo necessidade. */
	//Grau de necessidade (necessária/derivada)
	private Integer tipoNecessidade;
	
	/** The tipo efeito. */
	//Tipo do efeito (Indiferente, prevenção, correção)
	private Integer tipoEfeito;
	
	/** The tipo escopo. */
	//Escopo abrangido (Informação,Potência, mecânica, controle)
	private Integer tipoEscopo;
	//============================================================
	
	/**
	 * Instantiates a new funcao caso.
	 */
	public FuncaoCaso() {
	}

	/**
	 * Instantiates a new funcao caso.
	 *
	 * @param idFuncao the id funcao
	 */
	public FuncaoCaso(Integer idFuncao) {
		this.idFuncaoCaso = idFuncao;
	}

	/**
	 * Gets the id funcao caso.
	 *
	 * @return the id funcao caso
	 */
	//============================================================
	@Id
	@Column(name = "id_funcao_caso")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdFuncaoCaso() {
		return this.idFuncaoCaso;
	}

	/**
	 * Sets the id funcao caso.
	 *
	 * @param idFuncaoCaso the new id funcao caso
	 */
	public void setIdFuncaoCaso(Integer idFuncaoCaso) {
		this.idFuncaoCaso = idFuncaoCaso;
	}

	/**
	 * Gets the id funcao pai.
	 *
	 * @return the id funcao pai
	 */
	//============================================================
	@Column(name = "id_funcao_pai")
	public Integer getIdFuncaoPai() {
		return this.idFuncaoPai;
	}

	/**
	 * Sets the id funcao pai.
	 *
	 * @param idFuncaoPai the new id funcao pai
	 */
	public void setIdFuncaoPai(Integer idFuncaoPai) {
		this.idFuncaoPai = idFuncaoPai;
	}

	/**
	 * Gets the id funcao.
	 *
	 * @return the id funcao
	 */
	//============================================================
	@Column(name = "id_funcao")
	public Integer getIdFuncao() {
		return idFuncao;
	}

	/**
	 * Sets the id funcao.
	 *
	 * @param idFuncao the new id funcao
	 */
	public void setIdFuncao(Integer idFuncao) {
		this.idFuncao = idFuncao;
	}

	/**
	 * Gets the bol elementar.
	 *
	 * @return the bol elementar
	 */
	//============================================================
	@Column(name = "bol_elementar")
	public boolean getBolElementar() {
		return bolElementar;
	}

	/**
	 * Sets the bol elementar.
	 *
	 * @param bolElementar the new bol elementar
	 */
	public void setBolElementar(boolean bolElementar) {
		this.bolElementar = bolElementar;
	}

	/**
	 * Gets the tipo funcao.
	 *
	 * @return the tipo funcao
	 */
	//============================================================
	@Column(name = "tipo_funcao")
	public Integer getTipoFuncao() {
		return tipoFuncao;
	}

	/**
	 * Sets the tipo funcao.
	 *
	 * @param tipoFuncao the new tipo funcao
	 */
	public void setTipoFuncao(Integer tipoFuncao) {
		this.tipoFuncao = tipoFuncao;
	}

	/**
	 * Gets the tipo necessidade.
	 *
	 * @return the tipo necessidade
	 */
	//============================================================
	@Column(name = "tipo_necessidade")
	public Integer getTipoNecessidade() {
		return tipoNecessidade;
	}

	/**
	 * Sets the tipo necessidade.
	 *
	 * @param tipoNecessidade the new tipo necessidade
	 */
	public void setTipoNecessidade(Integer tipoNecessidade) {
		this.tipoNecessidade = tipoNecessidade;
	}

	/**
	 * Gets the tipo efeito.
	 *
	 * @return the tipo efeito
	 */
	//============================================================
	@Column(name = "tipo_efeito")
	public Integer getTipoEfeito() {
		return tipoEfeito;
	}

	/**
	 * Sets the tipo efeito.
	 *
	 * @param tipoEfeito the new tipo efeito
	 */
	public void setTipoEfeito(Integer tipoEfeito) {
		this.tipoEfeito = tipoEfeito;
	}

	/**
	 * Gets the tipo escopo.
	 *
	 * @return the tipo escopo
	 */
	//============================================================
	@Column(name = "tipo_escopo")
	public Integer getTipoEscopo() {
		return tipoEscopo;
	}

	/**
	 * Sets the tipo escopo.
	 *
	 * @param tipoEscopo the new tipo escopo
	 */
	public void setTipoEscopo(Integer tipoEscopo) {
		this.tipoEscopo = tipoEscopo;
	}
}
