/*
 * 
 */
package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * ImagemConceito generated by hbm2java.
 */
@Entity
@Table(name = "ImagemConceito")
public class ImagemConceito implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 4713779139866580922L;
	
	/** The id imagem. */
	private Integer idImagem;
	
	/** The dir imagem conceito. */
	private String dirImagemConceito;

	/**
	 * Instantiates a new imagem conceito.
	 */
	public ImagemConceito() {
	}

	/**
	 * Instantiates a new imagem conceito.
	 *
	 * @param idImagem the id imagem
	 */
	public ImagemConceito(Integer idImagem) {
		this.idImagem = idImagem;
	}

	/**
	 * Instantiates a new imagem conceito.
	 *
	 * @param idImagem the id imagem
	 * @param dirImagemConceito the dir imagem conceito
	 */
	public ImagemConceito(Integer idImagem, String dirImagemConceito) {
		this.idImagem = idImagem;
		this.dirImagemConceito = dirImagemConceito;
	}

	/**
	 * Gets the id imagem.
	 *
	 * @return the id imagem
	 */
	@Id
	@Column(name = "id_imagem")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdImagem() {
		return this.idImagem;
	}

	/**
	 * Sets the id imagem.
	 *
	 * @param idImagem the new id imagem
	 */
	public void setIdImagem(Integer idImagem) {
		this.idImagem = idImagem;
	}

	/**
	 * Gets the dir imagem conceito.
	 *
	 * @return the dir imagem conceito
	 */
	@Column(name = "dir_imagem_conceito", length = 2000000000)
	public String getDirImagemConceito() {
		return this.dirImagemConceito;
	}

	/**
	 * Sets the dir imagem conceito.
	 *
	 * @param dirImagemConceito the new dir imagem conceito
	 */
	public void setDirImagemConceito(String dirImagemConceito) {
		this.dirImagemConceito = dirImagemConceito;
	}

}
