package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImagemConceito generated by hbm2java
 */
@Entity
@Table(name = "ImagemConceito")
public class ImagemConceito implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4713779139866580922L;
	
	private Integer idImagem;
	private String dirImagemConceito;

	public ImagemConceito() {
	}

	public ImagemConceito(Integer idImagem) {
		this.idImagem = idImagem;
	}

	public ImagemConceito(Integer idImagem, String dirImagemConceito) {
		this.idImagem = idImagem;
		this.dirImagemConceito = dirImagemConceito;
	}

	@Id
	@Column(name = "id_imagem")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdImagem() {
		return this.idImagem;
	}

	public void setIdImagem(Integer idImagem) {
		this.idImagem = idImagem;
	}

	@Column(name = "dir_imagem_conceito", length = 2000000000)
	public String getDirImagemConceito() {
		return this.dirImagemConceito;
	}

	public void setDirImagemConceito(String dirImagemConceito) {
		this.dirImagemConceito = dirImagemConceito;
	}

}
