/*
 * 
 */
package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * ItemAvaliacao generated by hbm2java.
 */
@Entity
@Table(name = "ItemAvaliacao")
public class ItemAvaliacao implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 958192460638480686L;
	
	/** The id item. */
	private Integer idItem;
	
	/** The id funcao elementar. */
	private Integer idFuncaoElementar;
	
	/** The id conceito. */
	private Integer idConceito;
	
	/** The int peso. */
	private Integer intPeso;
	
	/** The str atributo. */
	private String strAtributo;

	/**
	 * Instantiates a new item avaliacao.
	 */
	public ItemAvaliacao() {
	}

	/**
	 * Instantiates a new item avaliacao.
	 *
	 * @param idItem the id item
	 */
	public ItemAvaliacao(Integer idItem) {
		this.idItem = idItem;
	}

	/**
	 * Instantiates a new item avaliacao.
	 *
	 * @param idItem the id item
	 * @param idFuncaoElementar the id funcao elementar
	 * @param idConceito the id conceito
	 * @param intPeso the int peso
	 * @param strAtributo the str atributo
	 */
	public ItemAvaliacao(Integer idItem, Integer idFuncaoElementar,
			Integer idConceito, Integer intPeso, String strAtributo) {
		this.idItem = idItem;
		this.idFuncaoElementar = idFuncaoElementar;
		this.idConceito = idConceito;
		this.intPeso = intPeso;
		this.strAtributo = strAtributo;
	}

	/**
	 * Gets the id item.
	 *
	 * @return the id item
	 */
	@Id
	@Column(name = "id_item")
	public Integer getIdItem() {
		return this.idItem;
	}

	/**
	 * Sets the id item.
	 *
	 * @param idItem the new id item
	 */
	public void setIdItem(Integer idItem) {
		this.idItem = idItem;
	}

	/**
	 * Gets the id funcao elementar.
	 *
	 * @return the id funcao elementar
	 */
	@Column(name = "id_funcao_elementar")
	public Integer getIdFuncaoElementar() {
		return this.idFuncaoElementar;
	}

	/**
	 * Sets the id funcao elementar.
	 *
	 * @param idFuncaoElementar the new id funcao elementar
	 */
	public void setIdFuncaoElementar(Integer idFuncaoElementar) {
		this.idFuncaoElementar = idFuncaoElementar;
	}

	/**
	 * Gets the id conceito.
	 *
	 * @return the id conceito
	 */
	@Column(name = "id_conceito")
	public Integer getIdConceito() {
		return this.idConceito;
	}

	/**
	 * Sets the id conceito.
	 *
	 * @param idConceito the new id conceito
	 */
	public void setIdConceito(Integer idConceito) {
		this.idConceito = idConceito;
	}

	/**
	 * Gets the int peso.
	 *
	 * @return the int peso
	 */
	@Column(name = "int_peso")
	public Integer getIntPeso() {
		return this.intPeso;
	}

	/**
	 * Sets the int peso.
	 *
	 * @param intPeso the new int peso
	 */
	public void setIntPeso(Integer intPeso) {
		this.intPeso = intPeso;
	}

	/**
	 * Gets the str atributo.
	 *
	 * @return the str atributo
	 */
	@Column(name = "str_atributo", length = 2000000000)
	public String getStrAtributo() {
		return this.strAtributo;
	}

	/**
	 * Sets the str atributo.
	 *
	 * @param strAtributo the new str atributo
	 */
	public void setStrAtributo(String strAtributo) {
		this.strAtributo = strAtributo;
	}

}
