package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItemAvaliacao generated by hbm2java
 */
@Entity
@Table(name = "ItemAvaliacao")
public class ItemAvaliacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 958192460638480686L;
	
	private Integer idItem;
	private Integer idFuncaoElementar;
	private Integer idConceito;
	private Integer intPeso;
	private String strAtributo;

	public ItemAvaliacao() {
	}

	public ItemAvaliacao(Integer idItem) {
		this.idItem = idItem;
	}

	public ItemAvaliacao(Integer idItem, Integer idFuncaoElementar,
			Integer idConceito, Integer intPeso, String strAtributo) {
		this.idItem = idItem;
		this.idFuncaoElementar = idFuncaoElementar;
		this.idConceito = idConceito;
		this.intPeso = intPeso;
		this.strAtributo = strAtributo;
	}

	@Id
	@Column(name = "id_item")
	public Integer getIdItem() {
		return this.idItem;
	}

	public void setIdItem(Integer idItem) {
		this.idItem = idItem;
	}

	@Column(name = "id_funcao_elementar")
	public Integer getIdFuncaoElementar() {
		return this.idFuncaoElementar;
	}

	public void setIdFuncaoElementar(Integer idFuncaoElementar) {
		this.idFuncaoElementar = idFuncaoElementar;
	}

	@Column(name = "id_conceito")
	public Integer getIdConceito() {
		return this.idConceito;
	}

	public void setIdConceito(Integer idConceito) {
		this.idConceito = idConceito;
	}

	@Column(name = "int_peso")
	public Integer getIntPeso() {
		return this.intPeso;
	}

	public void setIntPeso(Integer intPeso) {
		this.intPeso = intPeso;
	}

	@Column(name = "str_atributo", length = 2000000000)
	public String getStrAtributo() {
		return this.strAtributo;
	}

	public void setStrAtributo(String strAtributo) {
		this.strAtributo = strAtributo;
	}

}
