/*
 * 
 */
package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * Palavra generated by hbm2java.
 */
@Entity
@Table(name = "Palavra")
public class Palavra implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 653752913977646636L;
	
	/** The id palavra. */
	private Integer idPalavra;
	
	/** The str palavra. */
	private String strPalavra;

	/**
	 * Instantiates a new palavra.
	 */
	public Palavra() {
	}

	/**
	 * Instantiates a new palavra.
	 *
	 * @param idPalavra the id palavra
	 */
	public Palavra(Integer idPalavra) {
		this.idPalavra = idPalavra;
	}

	/**
	 * Instantiates a new palavra.
	 *
	 * @param idPalavra the id palavra
	 * @param strPalavra the str palavra
	 */
	public Palavra(Integer idPalavra, String strPalavra) {
		this.idPalavra = idPalavra;
		this.strPalavra = strPalavra;
	}

	/**
	 * Gets the id palavra.
	 *
	 * @return the id palavra
	 */
	@Id
	@Column(name = "id_palavra")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdPalavra() {
		return this.idPalavra;
	}

	/**
	 * Sets the id palavra.
	 *
	 * @param idPalavra the new id palavra
	 */
	public void setIdPalavra(Integer idPalavra) {
		this.idPalavra = idPalavra;
	}

	/**
	 * Gets the str palavra.
	 *
	 * @return the str palavra
	 */
	@Column(name = "str_palavra", length = 2000000000)
	public String getStrPalavra() {
		return this.strPalavra;
	}

	/**
	 * Sets the str palavra.
	 *
	 * @param strPalavra the new str palavra
	 */
	public void setStrPalavra(String strPalavra) {
		this.strPalavra = strPalavra;
	}

}
