package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Palavra generated by hbm2java
 */
@Entity
@Table(name = "Palavra")
public class Palavra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 653752913977646636L;
	private Integer idPalavra;
	private String strPalavra;

	public Palavra() {
	}

	public Palavra(Integer idPalavra) {
		this.idPalavra = idPalavra;
	}

	public Palavra(Integer idPalavra, String strPalavra) {
		this.idPalavra = idPalavra;
		this.strPalavra = strPalavra;
	}

	@Id
	@Column(name = "id_palavra")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdPalavra() {
		return this.idPalavra;
	}

	public void setIdPalavra(Integer idPalavra) {
		this.idPalavra = idPalavra;
	}

	@Column(name = "str_palavra", length = 2000000000)
	public String getStrPalavra() {
		return this.strPalavra;
	}

	public void setStrPalavra(String strPalavra) {
		this.strPalavra = strPalavra;
	}

}
