/*
 * 
 */
package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * FuncaoParcial generated by hbm2java.
 */
@Entity
@Table(name = "Solucao")
public class Solucao implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = -4908688476247627544L;
	
	/** The id solucao. */
	private Integer idSolucao;
	
	/** The id caso. */
	private Integer idCaso;
	
	/** The id funcao. */
	private Integer idFuncao;
	
	/** The id conceito. */
	private Integer idConceito;

	/**
	 * Instantiates a new solucao.
	 */
	public Solucao() {
	}

	/**
	 * Instantiates a new solucao.
	 *
	 * @param idFuncao the id funcao
	 */
	public Solucao(Integer idFuncao) {
		this.idFuncao = idFuncao;
	}

	/**
	 * Instantiates a new solucao.
	 *
	 * @param idSolucao the id solucao
	 * @param idCaso the id caso
	 * @param idFuncao the id funcao
	 * @param idConceito the id conceito
	 */
	public Solucao(	Integer idSolucao, 
					Integer idCaso,
					Integer idFuncao, 
					Integer idConceito) {
		
		this.idSolucao = idSolucao;
		this.idCaso = idCaso;
		this.idFuncao = idFuncao;
		this.idConceito = idConceito;
	}

	/**
	 * Gets the id solucao.
	 *
	 * @return the id solucao
	 */
	@Id
	@Column(name = "id_solucao")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdSolucao() {
		return this.idSolucao;
	}

	/**
	 * Sets the id solucao.
	 *
	 * @param idSolucao the new id solucao
	 */
	public void setIdSolucao(Integer idSolucao) {
		this.idSolucao = idSolucao;
	}

	/**
	 * Gets the id caso.
	 *
	 * @return the id caso
	 */
	@Column(name = "id_caso")
	public Integer getIdCaso() {
		return this.idCaso;
	}

	/**
	 * Sets the id caso.
	 *
	 * @param idCaso the new id caso
	 */
	public void setIdCaso(Integer idCaso) {
		this.idCaso = idCaso;
	}

	/**
	 * Gets the id funcao.
	 *
	 * @return the id funcao
	 */
	@Column(name = "id_funcao")
	public Integer getIdFuncao() {
		return this.idFuncao;
	}

	/**
	 * Sets the id funcao.
	 *
	 * @param idFuncao the new id funcao
	 */
	public void setIdFuncao(Integer idFuncao) {
		this.idFuncao = idFuncao;
	}

	/**
	 * Gets the id conceito.
	 *
	 * @return the id conceito
	 */
	@Column(name = "id_conceito")
	public Integer getIdConceito() {
		return this.idConceito;
	}

	/**
	 * Sets the id conceito.
	 *
	 * @param idConceito the new id conceito
	 */
	public void setIdConceito(Integer idConceito) {
		this.idConceito = idConceito;
	}

}
