package br.unb.ppmec.cbrmeca.db.model;

// Generated May 25, 2016 11:48:00 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FuncaoParcial generated by hbm2java
 */
@Entity
@Table(name = "Solucao")
public class Solucao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4908688476247627544L;
	private Integer idSolucao;
	private Integer idCaso;
	private Integer idFuncao;
	private Integer idConceito;

	public Solucao() {
	}

	public Solucao(Integer idFuncao) {
		this.idFuncao = idFuncao;
	}

	public Solucao(	Integer idSolucao, 
					Integer idCaso,
					Integer idFuncao, 
					Integer idConceito) {
		
		this.idSolucao = idSolucao;
		this.idCaso = idCaso;
		this.idFuncao = idFuncao;
		this.idConceito = idConceito;
	}

	@Id
	@Column(name = "id_solucao")
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getIdSolucao() {
		return this.idSolucao;
	}

	public void setIdSolucao(Integer idSolucao) {
		this.idSolucao = idSolucao;
	}

	@Column(name = "id_caso")
	public Integer getIdCaso() {
		return this.idCaso;
	}

	public void setIdCaso(Integer idCaso) {
		this.idCaso = idCaso;
	}

	@Column(name = "id_funcao")
	public Integer getIdFuncao() {
		return this.idFuncao;
	}

	public void setIdFuncao(Integer idFuncao) {
		this.idFuncao = idFuncao;
	}

	@Column(name = "id_conceito")
	public Integer getIdConceito() {
		return this.idConceito;
	}

	public void setIdConceito(Integer idConceito) {
		this.idConceito = idConceito;
	}

}
